version: '3'
services:
  phpfpm:
    image: markoshust/magento-php:7.4-fpm-2
    container_name: app-php
    volumes:
      - ./:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: app-nginx
    ports:
      - "${NGINX_HTTP_PORT:-8090}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - "${NGINX_CONFIG_PATH:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf:ro"

  db:
    platform: linux/x86_64
    image: mysql:5.6.47
    container_name: app-db
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./etc/infrastructure/mysql/my.cnf:/etc/mysql/my.cnf
      - ./etc/database/base.sql:/docker-entrypoint-initdb.d/base.sql

networks:
  app-network:
    driver: bridge